# .github/FUNDING.yml

# GitHub Sponsors
github: evilegi

# Directly supported providers (use your IDs/handles)
patreon: 
open_collective: 
ko_fi: 

# Custom links (any URL: PayPal.me, Venmo)
custom:
  - "https://paypal.me/evilegi"
  - "https://venmo.com/u/evilegi"

